version: "3.9"
services:
  # api:
  #   build: .
  #   container_name: voxmind_api
  #   env_file: .env
  #   ports: ["8000:8000"]
  #   depends_on: [db, redis]
  #   volumes:
  #     - ./runtime:/app/runtime
  # worker:
  #   build: .
  #   container_name: voxmind_worker
  #   command: celery -A app.workers.celery_app.celery_app worker --loglevel=INFO -Q default,render,publish,analytics
  #   env_file: .env
  #   depends_on: [db, redis]
  #   volumes:
  #     - ./runtime:/app/runtime
  # beat:
  #   build: .
  #   container_name: voxmind_beat
  #   command: celery -A app.workers.celery_app.celery_app beat --loglevel=INFO
  #   env_file: .env
  #   depends_on: [db, redis]
  db:
    image: postgres:15
    container_name: voxmind_db
    environment:
      POSTGRES_DB: aicl
      POSTGRES_USER: aicl
      POSTGRES_PASSWORD: aicl
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: voxmind_redis
    ports: ["6379:6379"]

volumes:
  pgdata:
